const fs=require('fs'),path=require('path'); const {DatabaseSync}=require('node:sqlite'); let db;
const fresh=()=>({name:'Adventurer',hp:{current:100,max:100},mp:{current:100,max:100},stamina:{current:100,max:100},inventory:[],equipment:[],conditions:[],turn:0,history:[]});
function initDb(){let d=path.join(__dirname,'data');fs.mkdirSync(d,{recursive:true});db=new DatabaseSync(path.join(d,'rpg-engine.sqlite'));db.exec(`CREATE TABLE IF NOT EXISTS campaign_state(campaign TEXT PRIMARY KEY,state_json TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS event_ledger(id INTEGER PRIMARY KEY AUTOINCREMENT,campaign TEXT NOT NULL,created_at TEXT NOT NULL,type TEXT NOT NULL,detail TEXT NOT NULL);`)}
function save(c,s){let x={...s};delete x.history;db.prepare(`INSERT INTO campaign_state VALUES(?,?,?) ON CONFLICT(campaign) DO UPDATE SET state_json=excluded.state_json,updated_at=excluded.updated_at`).run(c,JSON.stringify(x),new Date().toISOString())}
function log(c,t,d){db.prepare(`INSERT INTO event_ledger(campaign,created_at,type,detail) VALUES(?,?,?,?)`).run(c,new Date().toISOString(),t,d)}
function get(c){let r=db.prepare(`SELECT state_json FROM campaign_state WHERE campaign=?`).get(c),s=r?JSON.parse(r.state_json):fresh();if(!r)save(c,s);s.history=db.prepare(`SELECT created_at,type,detail FROM event_ledger WHERE campaign=? ORDER BY id DESC LIMIT 50`).all(c);return s}
function apply(c,a,p={}){let s=get(c);if(a==='reset'){db.prepare(`DELETE FROM event_ledger WHERE campaign=?`).run(c);s=fresh();save(c,s);log(c,'RESET','State reset');return get(c)}if(a==='set_name'){let old=s.name;s.name=String(p.name).slice(0,120);log(c,'NAME',`${old} → ${s.name}`)}if(a==='resource_delta'){if(!['hp','mp','stamina'].includes(p.resource))throw Error('Bad resource');let q=s[p.resource],b=q.current;q.current=Math.max(0,Math.min(q.max,b+Number(p.delta||0)));log(c,p.resource.toUpperCase(),`${b} → ${q.current}`)}if(a==='inventory_add'){let n=String(p.name||'').trim(),q=Math.max(1,Math.floor(Number(p.qty||1)));if(!n)throw Error('Item required');let f=s.inventory.find(x=>x.name.toLowerCase()===n.toLowerCase());f?f.qty+=q:s.inventory.push({name:n,qty:q});log(c,'ITEM+',`${n} ×${q}`)}if(a==='condition_add'){let n=String(p.name||'').trim(),t=p.turns==null?null:Math.max(1,Math.floor(Number(p.turns)));if(!n)throw Error('Condition required');s.conditions.push({name:n,turns:t});log(c,'CONDITION+',n)}if(a==='next_turn'){s.turn++;let ex=[];s.conditions.forEach(x=>{if(x.turns!=null&&--x.turns<=0)ex.push(x.name)});s.conditions=s.conditions.filter(x=>x.turns==null||x.turns>0);log(c,'TURN',`Turn ${s.turn}${ex.length?'; expired: '+ex.join(', '):''}`)}save(c,s);return get(c)}
async function init(router){initDb();router.get('/state',(req,res)=>{try{res.json({state:get(String(req.query.campaign||'global::default'))})}catch(e){res.status(500).json({error:e.message})}});router.post('/action',(req,res)=>{try{let {campaign='global::default',action,payload={}}=req.body||{};if(!action)return res.status(400).json({error:'action required'});res.json({state:apply(String(campaign),String(action),payload)})}catch(e){res.status(400).json({error:e.message})}});console.log('[ST RPG Engine] v0.1 loaded')}
async function exit(){try{db?.close()}catch{}}
module.exports={init,exit,info:{id:'st-rpg-engine',name:'ST RPG Engine',description:'Deterministic RPG state with SQLite persistence'}};